fix: #718 dragend don't fire on virtualization
KevinVandy/material-react-table pull request #719
Opened 2023-10-08 14:58 UTC by YongThePsibor

#718 
use `rangeExtractor` to keep `draggingRow` or `draggingColumn` in document.

2023-10-09 00:50 UTC, YongThePsibor commented
I'm new to github actions, can somebody tell me why it when wrong at Checkout Repository step? What should I do?

2023-10-09 03:26 UTC, KevinVandy requested changes
Overall, good solutions proposed, going to optimize a bit before merging.

2023-10-09 03:26 UTC, KevinVandy commented on packages/material-react-table/src/body/MRT_TableBody.tsx
> +  const draggingRowIndex = rows.findIndex((row) => row.id === draggingRow?.id);
this might introduce some performance overhead

2023-10-09 03:26 UTC, KevinVandy commented on packages/material-react-table/src/table/MRT_Table.tsx
> +    .findIndex((c) => c.id === draggingColumn?.id);
Another scanning of all rows potentially on every render, even if no dragging is occurring or the dragging features are not enabled

2023-10-12 03:17 UTC, KevinVandy approved these changes

2023-10-12 03:17 UTC, merged